### ISSUE TITLE
Jump + dodge causes animation tree to break

### ISSUE THREAD

**Issue by brian-holsters** [catprisbrey/Cats-Godot4-Modular-Souls-like-Template#4] opened 2024-02-23 19:00 UTC
When you land after jumping and dodging at the same time you are in a perpetual running state, even when standing still the run animation will keep playing.

**Comment by catprisbrey** [comment] 2024-02-23 23:29
This sounds like the bug from day 1 release that was patched. I can't seem to recreate the issue. Are you using the current build? Check the date of your download against the current branch.

**Comment by catprisbrey** [comment] 2024-02-25 14:06
If you can't confirm you're still having this issue on the latest build, I'm going to assume it's a duplicate from the v1.0.0 release day that was already patched and close this out.

Let me know, I'll give it a few more days.

**Comment by brian-holsters** [comment] 2024-02-28 10:42
I'll post a PR soon fixing this.

**Comment by brian-holsters** [comment] 2024-02-28 18:35
If you really don't believe this bug exists, start running and without releasing the run button, leave the control stick in neutral, you will start running in place

**Comment by catprisbrey** [comment] 2024-02-28 19:00
I agree, i was quick to assume you had a repeat issue. I apologize for that but your initial post of how to create the issue is unclear. You were talking about actions taken when jumping and dodging and so i was doing a lot of meddling with jumping and dodging and simply coudln't find what you were referring to.

Thanks for your later comment though about keeping the run button held and simply releasing the directional control. That very quickly confirmed the issue and led to a speedy fix. 

I strongly apologize for assuming it was a former bug, and i greatly appreciate your persistence in troubleshooting it with me. You've called me out on it, and the call out is warranted. I'll keep a more open mind moving forward for sure.

**Closed by catprisbrey** 2024-02-28 19:00 UTC
Labels: bug
